apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-optimizer-site-deployment
  namespace: devops-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-optimizer-site-pod-a
  template:
    metadata:
      labels:
        app: devops-optimizer-site-pod-a
    spec:
      containers:
      - name: devops-optimizer-site-pod-a
        image: acrtrg01dev01dopsoptimizer.azurecr.io/devops-team-image-pod-a:v10
        env:
           - name: SECRET_USERNAME
             valueFrom:
                secretKeyRef:
                  name: batchnumber
                  key: batchnumber
        imagePullPolicy: Always
        volumeMounts:          
              - name: vsts-pat
                mountPath: /etc/vsts-pat
              - name: emailcredentialsvolume
                mountPath: /etc/emailcredentials
              - name: dacredsvolume
                mountPath: /etc/dacreds
              
      volumes:
            - name: vsts-pat
              secret:
                secretName: vsts-pat
            - name: emailcredentialsvolume
              secret:
                secretName: emailcredentials
            - name: dacredsvolume
              secret:
                secretName: da-creds-lab
                  
---